spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-34-231-177-125.compute-1.amazonaws.com:5432/d3j5daug8vao2k
        username: xayixiqykujmzu
        password: a4e3e23b86301ffd3f467e7418f6fd50a682e477b5e7bb6422bb348671a700f6
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql

 

    jpa: 
        hibernate:
            ddl-auto: create-drop