spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://ec2-3-234-131-8.compute-1.amazonaws.com:5432/d8gi2gto40j796
        username: xafcnjfptygkda
        password: 1ae51343e5cdad55fcafdcbed0d1fc016694044b991bbebf67e96483f137f8c4
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql

 

    jpa: 
        hibernate:
            ddl-auto: create-drop